### ISSUE TITLE
"Invalid response header" with `CURLOPT_FILE` curl option

### ISSUE THREAD

**Issue by ilgazil** [anlutro/php-curl#65]
When using `CURLOPT_FILE` curl option to write huge contents into a file directly, the `Response` constructor tries to retrieve status code (which is not readable is this particular case) and leads to the `Invalid response header` exception.

```php
$target = fopen('/path/to/target', 'wb');

$request = (new cURL())
  ->newRequest('get', 'http://path/to/resource')
  ->setOption(CURLOPT_FILE, $target);

$response = $request->send();
```

**Comment by anlutro** [comment]
Thanks for the report, I wasn't aware of this flag! Fixed in 1.5.0 :)

**Comment by ilgazil** [comment]
Hey, thanks for having been that fast.
But you still parse headers in response constructor, so it still fails... I haven't dug further, but I don't think there is anything in response...

The following code (with working links so that you can copy/paste to try it)
```php
$curl = new cURL();

$file = fopen(realpath('.') . '/php-8.0.7.tar.gz', 'w');

$request = $curl
  ->newRequest('get', 'https://www.php.net/distributions/php-8.0.7.tar.gz')
  ->setOption(CURLOPT_FILE, $file)
  ->send();
```

Keeps throwing this exception:
```
PHP Fatal error:  Uncaught InvalidArgumentException: Invalid response header in /home/user/php-curl/vendor/anlutro/curl/src/Response.php:91
Stack trace:
#0 /home/user/php-curl/vendor/anlutro/curl/src/Response.php(74): anlutro\cURL\Response->parseHeaders()
#1 /home/user/php-curl/vendor/anlutro/curl/src/Response.php(61): anlutro\cURL\Response->parseHeader()
#2 /home/user/php-curl/vendor/anlutro/curl/src/cURL.php(333): anlutro\cURL\Response->__construct()
#3 /home/user/php-curl/vendor/anlutro/curl/src/cURL.php(292): anlutro\cURL\cURL->createResponseObject()
#4 /home/user/php-curl/vendor/anlutro/curl/src/Request.php(532): anlutro\cURL\cURL->sendRequest()
#5 /home/user/php-curl/index.php(12): anlutro\cURL\Request->send()
#6 {main}
  thrown in /home/user/php-curl/vendor/anlutro/curl/src/Response.php on line 91
```

The file is properly downloaded, but the script fails because being unable to get the response HTTP status code.

**Comment by anlutro** [comment]
The headers are part of the file that's downloaded, but there's something else going on here. I wrote a working test case but your example does indeed fail. I'll investigate further, it might be the combination of `CURLOPT_FILE` and something else, like gzip compression or HTTP/2.

**Comment by anlutro** [comment]
Seems like this has something to do with how the file handle is opened. If you open it in write-only mode, `fopen` just returns an empty string. However, using `w+` (same as `tmpfile` which I used in unit tests) doesn't seem to make a difference. I'll figure out a way to work around this.
